### ISSUE TITLE
Not working with new version of Give

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay-give#1]
Hello Team

On the old version of Give Plugin, it was working fine, but recently I updated Give to 2.9.5 and it stopped working. After filling in all the details, it is not getting redirecting to the payment gateway. Is it working for you with version 2.9.5?

**Comment by rvdsteege** [comment]
I'm still being redirected with Give version 2.9.5 and am unable to reproduce any issue.
