### ISSUE TITLE
Regarding Support for Visual Form Builder

### ISSUE THREAD

**Issue by knit-pay** [pronamic/wp-pronamic-pay-give#6]
Hello Team

Give has introduced Visual Form Builder in Give v3. This code is currently not compatible with Visual Form Builder, similar to Charitable https://github.com/pronamic/wp-pronamic-pay-charitable/issues/5

For old form builder Pronamic is available.
![image](https://github.com/pronamic/wp-pronamic-pay-give/assets/65900807/612668db-ad33-4dfc-9436-dcf1fa10506d)

For Visual Form Builder Pronamic is missing.
![image](https://github.com/pronamic/wp-pronamic-pay-give/assets/65900807/43794e1f-40d9-4634-929c-7b7c38c80ddc)

**Comment by rvdsteege** [comment]
I looked in to this a bit today and it seems that adding support for the visual form builder ("version 3") seems to require more or less a rewrite of the integration, which we currently don't have any plans for.

Give also states at https://givewp.com/documentation/core/givewp-3-0-compatibility-guide/ that the options-based editor won't go away soon:

> The GiveWP team is committed to maintaining support for any functionality currently possible, until that functionality can be reasonably and easily replicated in the new Form Editing experience. Forms created with the options-based form editor will be supported for the foreseeable future.

You're welcome to open a PR though. To add support you'd need to hook the action `givewp_register_payment_gateway` to register gateways that extends from `Give\Framework\PaymentGateways\PaymentGateway` (example at https://github.com/impress-org/givewp-example-gateway).

**Comment by rvdsteege** [comment]
Also enquired about in https://freescout.pronamic.nl/conversation/1887:

> Ik maak gebruik van de Pronamic Pay plugin om Buckaroo iDEAL te koppelen aan GiveWP. De betaalmethode was zichtbaar op het oude donatieformulier, maar nu met het nieuwe donatieformulier lijkt iDEAL niet zichtbaar te zijn.
>
> Kunnen jullie aangeven hoe ik iDEAL op het nieuwe donatieformulier kan laten weergeven? Zijn er specifieke instellingen of aanpassingen nodig om dit werkend te krijgen?
